# =============================================================================
# Akamai Inference Cloud — Makefile
# All access restricted to allowed_admin_cidr. No DNS. IP only.
# =============================================================================

SHELL := /bin/bash
.ONESHELL:
.DEFAULT_GOAL := help

TF_DIR        := terraform
KUBE_DIR      := kubernetes
SCRIPTS_DIR   := scripts
K6_DIR        := k6

# Node IPs — vLLM binds hostPort:8000 directly on the GPU node.
# Monitoring uses NodePorts (30000-32767 range) on the same node IPs.
CHICAGO_NODE_IP  ?= 172.238.162.106
SEATTLE_NODE_IP  ?= 172.232.182.27

# Kubeconfig files (generated by terraform apply)
KUBECONFIG_CHICAGO ?= $(CURDIR)/kubeconfig-chicago.yaml
KUBECONFIG_SEATTLE ?= $(CURDIR)/kubeconfig-seattle.yaml

KUBECTL_CHI := KUBECONFIG=$(KUBECONFIG_CHICAGO) kubectl
KUBECTL_SEA := KUBECONFIG=$(KUBECONFIG_SEATTLE) kubectl

# Aliases for Makefile rules that still reference VLLM_IP
CHICAGO_VLLM_IP := $(CHICAGO_NODE_IP)
SEATTLE_VLLM_IP := $(SEATTLE_NODE_IP)

# ── Help ──────────────────────────────────────────────────────────────────────
.PHONY: help
help:
	@echo ""
	@echo "  Akamai Inference Cloud"
	@echo "  ─────────────────────────────────────────────────────────────"
	@echo "  terraform-init      Initialize Terraform providers"
	@echo "  terraform-plan      Preview infrastructure changes"
	@echo "  terraform-apply     Create/update infrastructure"
	@echo "  terraform-destroy   Destroy ALL infrastructure (destructive)"
	@echo ""
	@echo "  deploy-all          Deploy all Kubernetes workloads"
	@echo "  deploy-chicago      Deploy workloads to Chicago cluster"
	@echo "  deploy-seattle      Deploy workloads to Seattle cluster"
	@echo ""
	@echo "  validate            Run all validation checks"
	@echo "  validate-gpu        Validate GPU availability"
	@echo "  validate-security   Validate IP allowlist on all services"
	@echo "  validate-vllm       Check vLLM health endpoints"
	@echo ""
	@echo "  test-smoke          Run smoke tests (k6)"
	@echo "  test-load           Run load tests (k6)"
	@echo "  test-stress         Run stress tests (k6)"
	@echo "  test-failover       Run failover tests (k6)"
	@echo ""
	@echo "  get-ips             Print all service endpoints"
	@echo "  start-local-router  Run multi-region router locally (port 8080)"
	@echo "  logs-vllm-chicago   Stream vLLM logs from Chicago"
	@echo "  logs-vllm-seattle   Stream vLLM logs from Seattle"
	@echo "  ─────────────────────────────────────────────────────────────"
	@echo ""

# ── Terraform ─────────────────────────────────────────────────────────────────
.PHONY: terraform-init
terraform-init:
	@echo "→ Initializing Terraform..."
	cd $(TF_DIR) && terraform init -upgrade

.PHONY: terraform-plan
terraform-plan:
	@echo "→ Planning Terraform..."
	cd $(TF_DIR) && terraform plan -out=tfplan

.PHONY: terraform-apply
terraform-apply:
	@echo "→ Applying Terraform (this creates real GPU instances)..."
	cd $(TF_DIR) && terraform apply tfplan
	@echo "→ Updating kubeconfigs..."
	$(SCRIPTS_DIR)/deploy-all.sh --kubeconfig-only

.PHONY: terraform-destroy
terraform-destroy:
	@echo "⚠️  WARNING: This will destroy ALL infrastructure including GPU nodes."
	@read -p "  Type 'destroy' to confirm: " confirm && [ "$$confirm" = "destroy" ]
	cd $(TF_DIR) && terraform destroy

.PHONY: terraform-output
terraform-output:
	cd $(TF_DIR) && terraform output

# ── Kubernetes Deploy ──────────────────────────────────────────────────────────
.PHONY: deploy-all
deploy-all:
	@echo "→ Deploying all workloads (Chicago + Seattle)..."
	bash $(SCRIPTS_DIR)/deploy-all.sh

.PHONY: deploy-chicago
deploy-chicago:
	@echo "→ Deploying workloads to Chicago..."
	bash $(SCRIPTS_DIR)/deploy-all.sh --region=chicago

.PHONY: deploy-seattle
deploy-seattle:
	@echo "→ Deploying workloads to Seattle..."
	bash $(SCRIPTS_DIR)/deploy-all.sh --region=seattle

# ── Validation ────────────────────────────────────────────────────────────────
.PHONY: validate
validate: validate-gpu validate-security validate-vllm
	@echo "✓ All validation checks passed"

.PHONY: validate-gpu
validate-gpu:
	@echo "→ Validating GPU availability..."
	bash $(SCRIPTS_DIR)/validate-gpu.sh

.PHONY: validate-security
validate-security:
	@echo "→ Validating IP allowlists..."
	bash $(SCRIPTS_DIR)/validate-ip-allowlist.sh

.PHONY: validate-vllm
validate-vllm:
	@echo "→ Checking vLLM health..."
	@curl -sf http://$(CHICAGO_NODE_IP):8000/health && echo "  ✓ Chicago vLLM healthy ($(CHICAGO_NODE_IP):8000)"
	@curl -sf http://$(SEATTLE_NODE_IP):8000/health && echo "  ✓ Seattle vLLM healthy ($(SEATTLE_NODE_IP):8000)"
	@curl -sf http://$(CHICAGO_NODE_IP):8080/health && echo "  ✓ Chicago router healthy ($(CHICAGO_NODE_IP):8080)"
	@curl -sf http://$(SEATTLE_NODE_IP):8080/health && echo "  ✓ Seattle router healthy ($(SEATTLE_NODE_IP):8080)"

# ── Tests (k6) ────────────────────────────────────────────────────────────────
.PHONY: test-smoke
test-smoke:
	@echo "→ Running smoke tests..."
	@[ -n "$(CHICAGO_VLLM_IP)" ] || (echo "Set CHICAGO_VLLM_IP" && exit 1)
	k6 run --env BASE_URL=http://$(CHICAGO_VLLM_IP):8000 $(K6_DIR)/smoke.js

.PHONY: test-load
test-load:
	@echo "→ Running load tests..."
	@[ -n "$(CHICAGO_VLLM_IP)" ] || (echo "Set CHICAGO_VLLM_IP" && exit 1)
	k6 run --env BASE_URL=http://$(CHICAGO_VLLM_IP):8000 $(K6_DIR)/load.js

.PHONY: test-stress
test-stress:
	@echo "→ Running stress tests..."
	@[ -n "$(CHICAGO_VLLM_IP)" ] || (echo "Set CHICAGO_VLLM_IP" && exit 1)
	k6 run --env BASE_URL=http://$(CHICAGO_VLLM_IP):8000 $(K6_DIR)/stress.js

.PHONY: test-failover
test-failover:
	@echo "→ Running failover tests..."
	@[ -n "$(CHICAGO_VLLM_IP)" ] || (echo "Set CHICAGO_VLLM_IP" && exit 1)
	@[ -n "$(SEATTLE_VLLM_IP)" ] || (echo "Set SEATTLE_VLLM_IP" && exit 1)
	bash $(SCRIPTS_DIR)/test-routing.sh
	k6 run \
		--env BASE_URL_CHICAGO=http://$(CHICAGO_VLLM_IP):8000 \
		--env BASE_URL_SEATTLE=http://$(SEATTLE_VLLM_IP):8000 \
		$(K6_DIR)/failover.js

# ── Utilities ─────────────────────────────────────────────────────────────────
.PHONY: get-ips
get-ips:
	@echo ""
	@echo "  ═══════════════════════════════════════════════════════"
	@echo "   Akamai Inference Cloud — Live Endpoints"
	@echo "  ═══════════════════════════════════════════════════════"
	@echo "   Chicago (us-ord)   node: $(CHICAGO_NODE_IP)"
	@echo "     vLLM API    →  http://$(CHICAGO_NODE_IP):8000/v1"
	@echo "     Router      →  http://$(CHICAGO_NODE_IP):8080/v1"
	@echo "     Prometheus  →  http://$(CHICAGO_NODE_IP):32448"
	@echo "     Grafana     →  http://$(CHICAGO_NODE_IP):30463  (admin/admin)"
	@echo ""
	@echo "   Seattle (us-sea)   node: $(SEATTLE_NODE_IP)"
	@echo "     vLLM API    →  http://$(SEATTLE_NODE_IP):8000/v1"
	@echo "     Router      →  http://$(SEATTLE_NODE_IP):8080/v1"
	@echo "     Prometheus  →  http://$(SEATTLE_NODE_IP):32152"
	@echo "     Grafana     →  http://$(SEATTLE_NODE_IP):31129  (admin/admin)"
	@echo "  ═══════════════════════════════════════════════════════"
	@echo ""

.PHONY: start-local-router
start-local-router:
	@echo "→ Starting multi-region router locally on :8080"
	@echo "  Chicago vLLM: http://$(CHICAGO_NODE_IP):8000"
	@echo "  Seattle vLLM: http://$(SEATTLE_NODE_IP):8000"
	CHICAGO_VLLM_URL=http://$(CHICAGO_NODE_IP):8000 \
	SEATTLE_VLLM_URL=http://$(SEATTLE_NODE_IP):8000 \
	ALLOWED_ADMIN_CIDR=177.181.2.218/32 \
	PORT=8080 \
	node router/src/index.js

.PHONY: logs-vllm-chicago
logs-vllm-chicago:
	$(KUBECTL_CHI) logs -f -l app=vllm -n inference

.PHONY: logs-vllm-seattle
logs-vllm-seattle:
	$(KUBECTL_SEA) logs -f -l app=vllm -n inference

.PHONY: gpu-status
gpu-status:
	@echo "=== GPU Status — Chicago ==="
	@$(KUBECTL_CHI) get nodes -o wide 2>/dev/null
	@echo ""
	@echo "=== GPU Status — Seattle ==="
	@$(KUBECTL_SEA) get nodes -o wide 2>/dev/null

.PHONY: pods
pods:
	@echo "=== Pods — Chicago ==="
	@$(KUBECTL_CHI) get pods -A 2>/dev/null
	@echo ""
	@echo "=== Pods — Seattle ==="
	@$(KUBECTL_SEA) get pods -A 2>/dev/null
